version: '2.1'

services:
  tollfee:
    build: microservices/tollfee-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mongodb:
        condition: service_healthy

  tollfeecalculator:
    build: microservices/tollfeecalculator-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  tollfee-composite:
    build: microservices/tollfee-composite-service
    mem_limit: 350m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  # $ mongo
  mongodb:
    image: mongo:3.6.9
    mem_limit: 350m
    ports:
      - "27017:27017"
    command: mongod --smallfiles
    environment:
      - MONGO_URI=mongodb://mongodb:27017/tollfeeservice-db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo MONGO_URI --quiet
      interval: 10s
      timeout: 10s
      retries: 5
