server.port: 7001
server.error.include-message: always

logging:
  level:
    root: INFO
    se.ahmed: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

spring.data.mongodb:
  host: localhost
  port: 27017
  database: tollfeeservice-db

---

spring.data.mongodb.host: mongodb

spring.profiles: docker

server.port: 8080